# action.yml
name: 'Tag Distributable Artifact'
description: 'Build the dist files of a repo and create a Git tag.'
inputs:
  tag_version:             # id of input
    description: 'Tag Version'
    required: true
    default: ''
  file_to_bump_version:    # id of input
    description: 'File path in which to bump the version string'
    required: true
    default: ''
  folders_to_check:        # id of input
    description: 'Space-separated list of folders to verify exist'
    required: false
    default: ''
  node_version:            # id of input
    description: 'Node.js version for the Docker build (e.g. 14.4.0 or 22.17.0)'
    required: false
    default: '14.4.0'
  alpine_version:          # id of input
    description: 'Alpine Linux version for the Docker build (e.g. 3.12 or 3.22.0)'
    required: false
    default: '3.12'

runs:
  using: 'docker'
  image:
    build:
      dockerfile: Dockerfile     # the Dockerfile in this repo
      args:
        NODE_VERSION: ${{ inputs.node_version }}
        ALPINE_VERSION: ${{ inputs.alpine_version }}
  args:
    - ${{ inputs.tag_version }}
    - ${{ inputs.file_to_bump_version }}
    - ${{ inputs.folders_to_check }}
