# action.yml
name: 'Tag Distributable Artifact'
description: 'Build the dist files of a repo and add it as a tag.'
inputs:
  tag_version:  # id of input
    description: 'Tag Version'
    required: true
    default: ''
  file_to_bump_version:  # id of input
    description: 'Name of the file to bump version string'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag_version }}
    - ${{ inputs.file_to_bump_version }}