name: "Tag Distributable Artifact"
description: "Build the dist files of a repo and add it as a tag."

inputs:
  tag_version:
    description: "Tag Version"
    required: true
  file_to_bump_version:
    description: "Name of the file to bump version string"
    required: true
  folders_to_check:
    description: "Space-separated list of folders to verify after build"
    required: false
    default: ""
  node_version:
    description: "Node version (e.g., 22, 22.17.0, 14.21.3, lts)"
    required: false
    default: "22"

runs:
  using: docker
  image: docker/Dockerfile.node14
  args:
    - ${{ inputs.tag_version }}
    - ${{ inputs.file_to_bump_version }}
    - ${{ inputs.folders_to_check }}