# action.yml
name: 'Tag Distributable Artifact'
description: 'Build the dist files of a repo and add it as a tag.'
inputs:
  tag_version:  # id of input
    description: 'Tag Version'
    required: true
    default: ''
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}